apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: openshift-prometheus
spec:
  datasources:
    - jsonData:
        interval: '5'
        tlsSkipVerify: true
        httpHeaderName1: Authorization
      secureJsonData:
        httpHeaderValue1: Bearer $GRAFANA_SA_TOKEN
      name: openshift-prometheus
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
      access: proxy
      isDefault: true
  name: openshift-prometheus